apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-cqb3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-cqb3
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-cqb3
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-cqb3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-cqb3
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-tvso-tenant/appstudio/dc-metro-map-cqb3@sha256:1989ff5d4bd20efdcef96f40abe2d43279478a4a8b793b79d0b06ca035f8353c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
